@startuml
top to bottom direction
package Global {
    !include Entite/entite.puml
    !include Architecture/architecture.puml
    !include Exploration/exploration.puml
    !include Plannification/plannification.puml
    !include Graphique/graphique.puml

    Camion --> Rue
    Camion --> Arc
    Encombrant --> Rue
    Encombrant --> Arc
    Dijkstra --> Sommets
    BFS --> Sommets
    GraphismeControle --> Arc : "utilise"
}

@enduml