@startuml
package Global {
    !include Entite/entite.puml
    !include Architecture/architecture.puml
    !include Exploration/exploration.puml
    !include Plannification/plannification.puml
    !include Graphique/graphique.puml

    class Main {
        + static Map<String, Set<GraphismeControle.Arc>> construireGraphe(Fichier fichier)
        + static void main(String[] args)
    }

    Camion --> Rue
    Camion --> Arc
    Encombrant --> Rue
    Encombrant --> Arc
    Dijkstra --> Sommets
    BFS --> Sommets
    GraphismeControle --> Arc : "utilise"
}
@enduml