@startuml
package Global.Planification {

    class Tournee {
        - LocalDate date
        - String type_dechet
        - String type_tournee
        - List<Arc> liste
        + Tournee(LocalDate date, String type_dechet, String type_tournee)
        + LocalDate getDate()
        + String getType_dechet()
        + String getType_tournee()
        + List<Arc> getListe()
        + void setListe(List<Arc> liste)
    }

    class Calendrier {
        - Map<LocalDate, Tournee> planning
        + void addTournee(Tournee t)
        + Tournee getTournee(LocalDate date)
        + void affichage(int annee)
    }

    class Planifier {
        + String[] type_dechet
        - Map<String, List<DayOfWeek>> joursParType
        - Map<String, Double> frequence
        + Planifier(Map<String, List<DayOfWeek>> joursParType, Map<String, Double> frequence)
        + Calendrier creerPlanning(int annee)
        + void addTournee(LocalDate d, String type_dechet, String type_tournee, Calendrier calendrier, List<DayOfWeek> joursAutorises)
    }

    Planifier --> Tournee : "instancie"
}
@enduml
